# Generated by Django 6.1 on 2026-09-04 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiSoHieuSuat',
            fields=[
                ('ma_cs', models.AutoField(db_column='MaCS', primary_key=True, serialize=False)),
                ('thoi_gian_ghi_nhan', models.DateTimeField(blank=True, db_column='ThoiGianGhiNhan', null=True)),
                ('do_tre', models.FloatField(blank=True, db_column='DoTre', null=True)),
                ('mat_goi', models.FloatField(blank=True, db_column='MatGoi', null=True)),
                ('bang_thong_su_dung', models.FloatField(blank=True, db_column='BangThongSuDung', null=True)),
            ],
            options={
                'db_table': 'ChiSoHieuSuat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LienKet',
            fields=[
                ('ma_lk', models.AutoField(db_column='MaLK', primary_key=True, serialize=False)),
                ('bang_thong_toi_da', models.FloatField(blank=True, db_column='BangThongToiDa', null=True)),
            ],
            options={
                'db_table': 'LienKet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoHong',
            fields=[
                ('ma_lh', models.AutoField(db_column='MaLH', primary_key=True, serialize=False)),
                ('ten_lo_hong', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TenLoHong', max_length=200, null=True)),
                ('muc_do', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MucDo', max_length=20, null=True)),
                ('trang_thai_khac_phuc', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TrangThaiKhacPhuc', max_length=20, null=True)),
                ('thoi_gian_xay_ra_su_co', models.DateTimeField(blank=True, db_column='ThoiGianXayRaSuCo', null=True)),
                ('thoi_gian_xu_ly_su_co', models.DateTimeField(blank=True, db_column='ThoiGianXuLySuCo', null=True)),
            ],
            options={
                'db_table': 'LoHong',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('ma_nv', models.AutoField(db_column='MaNV', primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='HoTen', max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Email', max_length=100, null=True, unique=True)),
                ('so_dien_thoai', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='SoDienThoai', max_length=15, null=True)),
                ('vai_tro', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='VaiTro', max_length=50, null=True)),
                ('chuyen_mon', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ChuyenMon', max_length=100, null=True)),
            ],
            options={
                'db_table': 'NhanVien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NhatKyLoi',
            fields=[
                ('ma_loi', models.AutoField(db_column='MaLoi', primary_key=True, serialize=False)),
                ('thoi_gian_loi', models.DateTimeField(blank=True, db_column='ThoiGianLoi', null=True)),
                ('mo_ta_loi', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MoTaLoi', null=True)),
                ('muc_do_nghiem_trong', models.IntegerField(blank=True, db_column='MucDoNghiemTrong', null=True)),
                ('da_xu_ly', models.BooleanField(db_column='DaXuLy')),
                ('thoi_gian_hoan_thanh', models.DateTimeField(blank=True, db_column='ThoiGianHoanThanh', null=True)),
            ],
            options={
                'db_table': 'NhatKyLoi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThietBi',
            fields=[
                ('ma_tb', models.AutoField(db_column='MaTB', primary_key=True, serialize=False)),
                ('ten_tb', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TenTB', max_length=100, null=True)),
                ('loai_tb', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LoaiTB', max_length=50, null=True)),
                ('dia_chi_ip', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DiaChiIP', max_length=15, null=True, unique=True)),
                ('vi_tri', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ViTri', max_length=200, null=True)),
                ('trang_thai', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TrangThai', max_length=20, null=True)),
                ('tinh_trang', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TinhTrang', max_length=20)),
            ],
            options={
                'db_table': 'ThietBi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nhan_vien', models.OneToOneField(db_column='MaNV', on_delete=django.db.models.deletion.PROTECT, related_name='user_account', to='qlmvt.nhanvien')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_useraccount',
            },
        ),
    ]
