GRANT SELECT, INSERT, UPDATE, DELETE ON NhanVien TO AdminRole;
GRANT SELECT, INSERT, UPDATE, DELETE ON ThietBi TO AdminRole;
GRANT SELECT, INSERT, UPDATE, DELETE ON LienKet TO AdminRole;
GRANT SELECT, INSERT, UPDATE, DELETE ON ChiSoHieuSuat TO AdminRole;
GRANT SELECT, INSERT, UPDATE, DELETE ON NhatKyLoi TO AdminRole;
GO